services:
  pdf-service:
    build: .
    container_name: pdf-service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/app/public
    networks:
      - pdf-service-network

  pdf-service-https:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    depends_on:
      - pdf-service
    networks:
      - pdf-service-network
  

networks:
  pdf-service-network:
    external: true
    name: pdf-service-network